// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateVideo(arg1) {
  return window['go']['main']['App']['CreateVideo'](arg1);
}

export function DeleteVideo(arg1) {
  return window['go']['main']['App']['DeleteVideo'](arg1);
}

export function DetectChromePath() {
  return window['go']['main']['App']['DetectChromePath']();
}

export function GetCDPStatus() {
  return window['go']['main']['App']['GetCDPStatus']();
}

export function GetSelectorConfigPath() {
  return window['go']['main']['App']['GetSelectorConfigPath']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function LaunchChromeCDP() {
  return window['go']['main']['App']['LaunchChromeCDP']();
}

export function ListVideos() {
  return window['go']['main']['App']['ListVideos']();
}

export function OpenPathInOS(arg1) {
  return window['go']['main']['App']['OpenPathInOS'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SelectFolder() {
  return window['go']['main']['App']['SelectFolder']();
}

export function TestCDPConnection() {
  return window['go']['main']['App']['TestCDPConnection']();
}
