// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {types} from '../models';

export function CreateVideo(arg1:types.CreateVideoRequest):Promise<types.Video>;

export function DeleteVideo(arg1:string):Promise<void>;

export function DetectChromePath():Promise<string>;

export function GetCDPStatus():Promise<types.CDPStatus>;

export function GetSelectorConfigPath():Promise<string>;

export function GetSettings():Promise<types.Settings>;

export function LaunchChromeCDP():Promise<types.CDPStatus>;

export function ListVideos():Promise<Array<types.Video>>;

export function OpenPathInOS(arg1:string):Promise<void>;

export function SaveSettings(arg1:types.Settings):Promise<types.Settings>;

export function SelectFolder():Promise<string>;

export function TestCDPConnection():Promise<types.CDPStatus>;
